*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 28.10.2006 at 17:34:12 by user U255290
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZTEST_45101TOP.                   " Global Data
  INCLUDE LZTEST_45101UXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZTEST_45101F00                         . " subprograms
  INCLUDE LZTEST_45101I00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZTEST_45101F...                   " Subprograms
* INCLUDE LZTEST_45101O...                   " PBO-Modules
* INCLUDE LZTEST_45101I...                   " PAI-Modules
